package br.com.entelgy;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'falvojr' at '9/14/16 12:05 AM' with Gradle 2.14.1
 *
 * @author falvojr, @date 9/14/16 12:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
