package br.com.entelgy;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'falvojr' at '9/14/16 12:05 AM' with Gradle 2.14.1
 *
 * @author falvojr, @date 9/14/16 12:05 AM
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
